name: "Genesis Validation"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-genesis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: go version
      - name: Install dependencies
        run: sudo apt install -y boxes moreutils coreutils
      - name: Run genesis validation
        run: |
          bash -x ./validate-genesis.sh
        env:
          DAEMON: ./build/evmosd
          CHAIN_ID: evmos_9001-1
          DENOM: aevmos
          GH_URL: https://github.com/tharsis/evmos
          BINARY_VERSION: v1.1.0
          PROJECT_DIR: ${{ github.workspace }}
